name: motocheck
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  get: 4.6.5
  remixicon: ^1.0.0
  side_sheet: ^1.0.2
  websafe_svg: ^2.1.2+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/pictures/
    - assets/svgs/

  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/sofia/sofiapro-light.otf

    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend/LexendDeca-Thin.ttf
          weight: 100

        - asset: assets/fonts/lexend/LexendDeca-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/lexend/LexendDeca-Light.ttf
          weight: 300

        - asset: assets/fonts/lexend/LexendDeca-Regular.ttf
          weight: 400

        - asset: assets/fonts/lexend/LexendDeca-Medium.ttf
          weight: 500

        - asset: assets/fonts/lexend/LexendDeca-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/lexend/LexendDeca-Bold.ttf
          weight: 700

        - asset: assets/fonts/lexend/LexendDeca-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/lexend/LexendDeca-Black.ttf
          weight: 900
